module.exports = {
	printWidth: 200,
	semi: true,
	tabWidth: 4,
	useTabs: true,
	singleQuote: true,
	trailingComma: 'es5',
	bracketSpacing: true,
	htmlWhitespaceSensitivity: 'ignore',
	parsers: {
		'.jsx': 'flow',
		'.scss': 'scss',
		'.ts': 'typescript',
		'.less': 'css',
		'.vue': 'vue',
		'.nvue': 'vue',
		'.ux': 'vue',
		'.yml': 'yaml',
	},
};
